version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
    environment:
      - APP_ENV=local
  frontend:
    build:
      context: ./frontend
    command: npm run dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    working_dir: /app